name=HomeAssistantArduinoMQTT
version=1.0.0
author=Alberto Bettin
maintainer=Alberto Bettin
sentence=Home Assistant MQTT library.
paragraph=Arduino Library to connect devices to Home Assistant via MQTT.
category=Communication
url=https://github.com/Bettapro/HomeAssistantArduinoMQTT
architectures=*
includes=HomeAssistantArduinoMQTT.h
depends=PubSubClient