name=HomeAssistantArduinoMQTT
version=0.0.0
author=Alberto Bettin
maintainer=Alberto Bettin
sentence=Home Assistant MQTT library.
paragraph=Arduino Library to connect devices to Home Assistant via MQTT.
category=Communication
url=https://github.com/Bettapro/HomeAssistantArduinoMQTT
architectures=esp8266,esp32
includes=HomeAssistantArduinoMQTT.h
depends=ArduinoJson, PubSubClient